### ISSUE TITLE
how to add more multiple user ID?

### ISSUE THREAD

**Issue by SoundDr0ut** [nicokempe/discord-tracker#92]
![image](https://github.com/user-attachments/assets/57e3ecba-30fd-488a-9ce8-1b821f06fd48)

**Comment by nicokempe** [comment]
Hi, like already written on Discord: I have already written that in a minimal version but it is not natively supported at the moment. I can look into that and add this feature when I have time for that. 👍

**Comment by nicokempe** [comment]
Done. You can now use the `config/users.json` file to configure as many users in as many activity channels you want.

**Comment by SoundDr0ut** [comment]
> Done. You can now use the `config/users.json` file to configure as many users in as many activity channels you want.

unfortunately our bot doesnt send status logs to specified channel

**Comment by nicokempe** [comment]
> > Done. You can now use the `config/users.json` file to configure as many users in as many activity channels you want.
> 
> unfortunately our bot doesnt send status logs to specified channel

I tested it on my Discord and it worked just fine, could you provide the log files to see if there are any errors? Or could you provide more information about the enviroment (your users.json and any other information that may help me to troubleshoot the problem)?

**Comment by SoundDr0ut** [comment]
> > > Done. You can now use the `config/users.json` file to configure as many users in as many activity channels you want.
> > 
> > 
> > unfortunately our bot doesnt send status logs to specified channel
> 
> I tested it on my Discord and it worked just fine, could you provide the log files to see if there are any errors? Or could you provide more information about the enviroment (your users.json and any other information that may help me to troubleshoot the problem)?

nvm its working now, thank you

**Comment by nicokempe** [comment]
No problem, glad it works now ^^
