### ISSUE TITLE
Add mention user instead of display name

### ISSUE THREAD

**Issue by ShockAnWave** [nicokempe/discord-tracker#93]
![image](https://github.com/user-attachments/assets/ca16d7e8-f74b-4661-844c-03b7d4e605ed)

**Comment by nicokempe** [comment]
Hi @ShockAnWave,
I guess that could get annoying pretty fast, do you have a specific use-case where this still would make sense? I could of course just make it configurable in the config or add a user command so that users can opt-in but I would let the default to keep it like it is in the moment.

**Comment by ShockAnWave** [comment]
> Hi @ShockAnWave, I guess that could get annoying pretty fast, do you have a specific use-case where this still would make sense? I could of course just make it configurable in the config or add a user command so that users can opt-in but I would let the default to keep it like it is in the moment.

Can you add functions like mention user set true or false so it will be configurable, in the end you have the rights to do whatever u want

**Comment by nicokempe** [comment]
> Can you add functions like mention user set true or false so it will be configurable, in the end you have the rights to do whatever u want

Yes I will look into that when I got the time for that and I will keep you updated ^^

**Comment by ShockAnWave** [comment]
> > Can you add functions like mention user set true or false so it will be configurable, in the end you have the rights to do whatever u want
> 
> Yes I will look into that when I got the time for that and I will keep you updated ^^

appreciate it sir

**Comment by nicokempe** [comment]
Hi @ShockAnWave,

it is done! I have tested it with my user and toggled the setting and it works now. Let me know if there is anything else. ^^

Here a preview:

![image](https://github.com/user-attachments/assets/cbac2608-53c5-4c91-9d97-34b931e1812c)

**Comment by ShockAnWave** [comment]
> Hi @ShockAnWave,
> 
> it is done! I have tested it with my user and toggled the setting and it works now. Let me know if there is anything else. ^^
> 
> Here a preview:
> 
> ![image](https://private-user-images.githubusercontent.com/50241630/366917736-cbac2608-53c5-4c91-9d97-34b931e1812c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjQ5NjMsIm5iZiI6MTcyNjE2NDY2MywicGF0aCI6Ii81MDI0MTYzMC8zNjY5MTc3MzYtY2JhYzI2MDgtNTNjNS00YzkxLTlkOTctMzRiOTMxZTE4MTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE4MTEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNTYzOGNmYzk0NDE1MWQxODY3NDYzZDEyODA5NGNiNDk2M2NmMWIxZTkzOTVjZWM5NmUyYTZlMGZjMmNlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EyLrMBq-Hg4F9nAS0qvBLJDjp0-nTrHTvI_BjHp1AXw)

Thank you sir
